name: FOSSA
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.14.x"
      - run: go version
      # Runs a set of commands to initialize and analyze with FOSSA
      - name: run FOSSA analysis
        env:
          # FOSSA Push-Only API Token
          FOSSA_API_KEY: '1a92b8d8ee4304c0ad85a726b9e9acab'
          BINDIR: /home/runner/work/volcano/devices
        run: |
          export GOPATH=$HOME/go
          export PATH=$PATH:$(go env GOPATH)/bin
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash -s -- -b /home/runner/work/volcano/devices
          /home/runner/work/volcano/devices/fossa init
          /home/runner/work/volcano/devices/fossa analyze
      
      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - run: make ubuntu20.04
      - run: TAG_VERSION="${BRANCH_NAME}" make push-tag
      - run: make push-latest
